# -*- coding: utf-8 -*-
"""data processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpdEZ05l-ObD_XvBipcmF7EmJW4Qo7sb
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_path = '/content/drive/MyDrive/Internship/Bipi/whole_sales.csv'

sales = pd.read_csv(data_path)
sales.head()

sales[['skus', 'selling_price']].groupby(['skus']).sum().sort_values(by='selling_price', ascending=False)[:10].plot(kind='bar')
plt.title('Each Product Sales')
plt.xlabel('Product')
plt.ylabel('Sales')

sales[['product_category', 'selling_price']].groupby(['product_category']).sum().sort_values(by='selling_price', ascending=False)[:10].plot(kind='bar')
plt.title('Each Product Sales')
plt.xlabel('Product Category')
plt.ylabel('Sales')

sales[['merchant_id', 'product_category', 'selling_price']].groupby(['merchant_id', 'product_category']).sum().sort_values(by='selling_price', ascending=False)

sales.info()

sales['product_category'].value_counts().plot(kind='bar')
plt.title('Number of Product Category Sales')

sales['ordered_date'] = pd.to_datetime(sales['ordered_date'])

df = sales.copy()
df['month'] =  sales['ordered_date'].dt.month
df[(df['month'] == 3) & (df['cancel_status'] == 'F')][['skus', 'selling_price']].groupby(['skus']).sum().sort_values(by='selling_price', ascending=False)[:10].plot(kind='bar')
plt.title('Product Sales in March')
plt.xlabel('Product')
plt.ylabel('Sales')

df[(df['month'] == 4) & (df['cancel_status'] == 'F')][['skus', 'selling_price']].groupby(['skus']).sum().sort_values(by='selling_price', ascending=False)[:10].plot(kind='bar')
plt.title('Product Sales in April')
plt.xlabel('Product')
plt.ylabel('Sales')

df[(df['month'] == 5) & (df['cancel_status'] == 'F')][['skus', 'selling_price']].groupby(['skus']).sum().sort_values(by='selling_price', ascending=False)[:10].plot(kind='bar')
plt.title('Product Sales in May')
plt.xlabel('Product')
plt.ylabel('Sales')

df['month'].value_counts().sort_values().plot(kind='bar')

df[['month', 'selling_price']].groupby(['month']).sum().plot(kind='line')
plt.xticks([3, 4, 5])
plt.title('Month-to-Month Sales')
plt.xlabel('Month')
plt.ylabel('Sales')

